### ISSUE TITLE
shortkey of return the last line

### ISSUE THREAD

**Issue by roachsinai** [gabenespoli/vim-jupycent#1]
![image](https://user-images.githubusercontent.com/9500049/79250757-c05f3e80-7eb1-11ea-9f6c-ce24bccad91d.png)

Thanks for your plugin, but I have a question.

The shortkey is exactly: g\"zvzz``?

**Comment by gabenespoli** [comment]
Nice catch. TIL that you can't use a backslash to escape backticks in GitHub markdown. I've updated the README with the proper key sequence that is called: ``g`"zvzz``

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/79290780-903e8c80-7eff-11ea-9c54-5a53bbb4ebd7.png)

Hi, need on backslash, too.

**Comment by gabenespoli** [comment]
Thanks! Fixed.
