### ISSUE TITLE
[Feature] add a variable to set default python interpreter

### ISSUE THREAD

**Issue by roachsinai** [gabenespoli/vim-jupycent#2]
I install `jupytext` in a virtual environment created by pyenv. Is there a way to add a variable like `jupycent_python_interpreter_path` to avoid activate virtual environmen when open a single .ipynb file?

**Comment by gabenespoli** [comment]
You should be able to use `g:jupytext_command` for this. Something like `let g:jupycent_command = '/path/to/.pyenv/versions/myenv/bin/jupytext'`

**Comment by roachsinai** [comment]
Yeah, worked! Thanks for your reply!
